config/routes.rb
Rails.application.routes.draw do
  resources :imports
  root to: 'imports#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :orders
end

app/models/import.rb
class Import < ApplicationRecord
  has_one_attached :file
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  belongs_to :import
  belongs_to :product
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prices
  belongs_to :provider
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :edit, :update, :destroy]

  def index
    @imports = Import.all
  end

  def show
  end

  def new
    @import = Import.new
  end

  def create
    import_service = ImportService.new(import_params)
    @import = import_service.execute

    respond_to do |format|
      format.html { redirect_to @import, notice: t('import_success') }
    end
  rescue
    redirect_to :root, notice: t('import_fail')
  end

  private

  def set_import
    @import = Import.eager_load(orders: [:buyer, product: [:prices, :provider]]).find(params[:id])
  end

  def import_params
    params.require(:import).permit(:file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
  def currency(value)
    number_to_currency(value.to_f / 100, precision: 2)
  end
end

app/views/imports/_form.html.erb
<%= form_with(model: import, local: true, html: { multipart: true }) do |form| %>
  <% if import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
        <% import.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imports/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.import.other') %></h1>

<table>
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.import.created_at') %></th>
    <th><%= t('activerecord.attributes.import.total_value') %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @imports.each do |import| %>
    <tr>
      <td><%= l(import.created_at, format: :short) %></td>
      <td><%= currency(import.total_value) %></td>
      <td><%= link_to t('show'), import %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_import'), new_import_path %>

app/views/imports/new.html.erb
<h1><%= t('new_import') %></h1>

<%= render 'form', import: @import %>

<%= link_to t('back'), imports_path %>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.import.one') %></h1>

<table>
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.import.created_at') %></th>
    <th><%= t('activerecord.attributes.import.total_value') %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= l(@import.created_at, format: :short) %></td>
    <td><%= currency(@import.total_value) %></td>
  </tr>
  </tbody>
</table>

<h3><%= t('imported_items') %></h3>

<table>
  <thead>
  <tr>
    <th><%= t('activerecord.models.buyer.one') %></th>
    <th><%= t('activerecord.attributes.order.description') %></th>
    <th><%= t('activerecord.attributes.order.unit_price') %></th>
    <th><%= t('activerecord.attributes.order.quantity') %></th>
    <th><%= t('activerecord.attributes.order.total') %></th>
    <th><%= t('activerecord.attributes.buyer.address') %></th>
    <th><%= t('activerecord.models.provider.one') %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @import.orders.each do |order| %>
    <tr>
      <td><%= order.buyer.name %></td>
      <td><%= order.product.description %></td>
      <td><%= currency(order.unit_price) %></td>
      <td><%= order.quantity %></td>
      <td><%= currency(order.total_price) %></td>
      <td><%= order.buyer.address %></td>
      <td><%= order.product.provider.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>


</br>

<%= link_to t('back'), imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>